import fs from 'fs';

import dotenv from 'dotenv';
dotenv.config();

const {
  NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  NEXT_PUBLIC_FIREBASE_APP_ID
} = process.env;

const content = `const swEnv = {
    NEXT_PUBLIC_FIREBASE_API_KEY: '${NEXT_PUBLIC_FIREBASE_API_KEY}',
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: '${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}',
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: '${NEXT_PUBLIC_FIREBASE_PROJECT_ID}',
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: '${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}',
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}',
    NEXT_PUBLIC_FIREBASE_APP_ID: '${NEXT_PUBLIC_FIREBASE_APP_ID}',
 }`;

fs.writeFileSync('public/swEnv.js', content);
