import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.scss';
import 'tippy.js/dist/tippy.css';

const poppins = localFont({
  src: './fonts/Poppins-Regular.ttf',
  variable: '--font-poppins',
  weight: '100 900'
});

export const metadata: Metadata = {
  title: 'Telegram',
  description: 'Generated by create next app',

  // link to your manifest.json
  manifest: '/manifest.json',

  // theme-color for browsers (address-bar, splash screen background, etc)
  // icons for favicon, shortcut, Android, and the canonical iOS icon:
  // icons: {
  //   icon: '/favicon.ico',
  //   shortcut: '/icon.png',
  //   apple: '/apple-icon.png', // 180×180 “apple-touch-icon”
  //   other: [
  //     {
  //       rel: 'android-chrome-192x192',
  //       url: '/web-app-manifest-192x192.png',
  //       sizes: '192x192',
  //       type: 'image/png'
  //     },
  //     {
  //       rel: 'android-chrome-512x512',
  //       url: '/web-app-manifest-512x512.png',
  //       sizes: '512x512',
  //       type: 'image/png'
  //     }
  //   ]
  // },
  // TELL iOS SAFARI TO TREAT THIS AS A STANDALONE APP
  // appleWebApp: {
  //   capable: true, // <meta name="apple-mobile-web-app-capable" content="yes" />
  //   title: 'Messenger', // <meta name="apple-mobile-web-app-title" content="Messenger" />
  //   statusBarStyle: 'black-translucent' // <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  // },
  //
  // // OPTIONAL: extra one-off meta tags
  // other: {
  //   'theme-color': '#932828',
  //   'msapplication-TileColor': '#932828',
  //   'msapplication-TileImage': '/mstile-150x150.png'
  // }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased h-screen`}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
